
import java.sql.Connection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class frame2 extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    public frame2() {
      
        //getConnection();
        initComponents();
        Show_Product_In_JTable();
          }
String ImgPath=null;
int pos=0;
  
    public Connection getConnection(){
        Connection con =null;      
        try{
        Class.forName("org.apache.derby.jdbc.ClientDriver");
         con=DriverManager.getConnection("jdbc:derby://localhost:1527/store","omer","omer");
            // JOptionPane.showMessageDialog(null ,"connected");
             return con;
                }
                catch(Exception d){
                    System.out.println("error");
                return null;   
                }
    
    }
    
    public boolean checkInputs(){
        if(txt_name.getText()==null || txt_price.getText()==null)
            
        
        {
            return false;
        }
        else{
                try{
                Float.parseFloat(txt_price.getText());
                return true;
                }
                catch(Exception d){
                return false;
                }
    }
            
    }
    
    
    public ImageIcon ResizeImage(String imagePath,byte[] pic){
        ImageIcon myImage =null;
        if(imagePath!=null){
            myImage=new ImageIcon(imagePath);
        }
        else{
            myImage=new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2=img.getScaledInstance(lbl_image.getWidth(),lbl_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2); 
        return image;
    }
    //display data in Jtable
    //fill the ArrayList with data
    public ArrayList<Product> getProductList(){
        ArrayList<Product> productList = new ArrayList<Product>();
        Connection con = getConnection();
        String query = "Select * FROM product";
        Statement st;
        ResultSet rs;
        
        try{
  
        st = con.createStatement();
        rs = st.executeQuery(query);
        Product product;
        while(rs.next()){
            product = new Product(rs.getInt("id"),rs.getString("name"),Float.parseFloat(rs.getString("price")),rs.getBytes("image"));
            productList.add(product);
        }
        
    }
        catch(Exception e){
                System.out.println("sql error");
                }
    
        return productList;
        
    } 
    //2 populate the Jtable

    public void Show_Product_In_JTable(){
    ArrayList<Product> list = getProductList();
    DefaultTableModel model = (DefaultTableModel) JTable_Products.getModel();
    //clear jtable content
    model.setRowCount(0);
    Object[] row = new Object[3];
    for(int i=0; i<list.size();i++){
        row[0]=list.get(i).getId();
        row[1]=list.get(i).getname();
        row[2]=list.get(i).getPrice();
        
        model.addRow(row);
    }
    
    }     
   public void ShowItem(int index ){
 
       txt_id.setText(Integer.toString(getProductList().get(index).getId()));
       txt_name.setText(getProductList().get(index).getname());
       txt_price.setText(Float.toString(getProductList().get(index).getPrice()));
      lbl_image.setIcon(ResizeImage(null,getProductList().get(index).getImage()));
   }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Products = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Btn_Insert = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Btn_First = new javax.swing.JButton();
        Btn_Next = new javax.swing.JButton();
        Btn_Previous = new javax.swing.JButton();
        Btn_Last = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 30, 40, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 80, 60, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRICE:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 120, 70, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("IMAGE:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 160, 68, 22);

        txt_id.setBackground(new java.awt.Color(204, 204, 204));
        txt_id.setEnabled(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel2.add(txt_id);
        txt_id.setBounds(120, 40, 100, 30);

        txt_name.setBackground(new java.awt.Color(204, 204, 204));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_name);
        txt_name.setBounds(120, 80, 100, 30);

        txt_price.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(txt_price);
        txt_price.setBounds(120, 120, 100, 30);

        lbl_image.setBackground(new java.awt.Color(204, 204, 204));
        lbl_image.setOpaque(true);
        jPanel2.add(lbl_image);
        lbl_image.setBounds(120, 170, 180, 150);

        JTable_Products.setBackground(new java.awt.Color(204, 204, 204));
        JTable_Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "price"
            }
        ));
        JTable_Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_ProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_Products);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(360, 10, 360, 276);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 400, 100, 30);

        Btn_Insert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Insert.setText("insert");
        Btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InsertActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Insert);
        Btn_Insert.setBounds(30, 400, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(170, 400, 90, 30);

        jButton4.setText("Choose Image");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(130, 340, 158, 33);

        Btn_First.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_First.setText("first");
        Btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FirstActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_First);
        Btn_First.setBounds(370, 300, 73, 23);

        Btn_Next.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Next.setText("Next");
        Btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NextActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Next);
        Btn_Next.setBounds(460, 300, 73, 23);

        Btn_Previous.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Previous.setText("Previous");
        Btn_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PreviousActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Previous);
        Btn_Previous.setBounds(550, 300, 90, 23);

        Btn_Last.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Last.setText("last");
        Btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LastActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Last);
        Btn_Last.setBounds(650, 300, 73, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("BACK TO MAIN MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(520, 520, 190, 40);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 510);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(checkInputs() && txt_id.getText() !=null){
          String UpdateQuery=null;
          PreparedStatement ps= null;
        Connection con = getConnection();
       //udate without image
        if(ImgPath==null){
            try {
                   UpdateQuery= "update product set name = ?, price = ? WHERE id = ? ";
                  ps = con.prepareStatement(UpdateQuery);
                  ps.setString(1,txt_name.getText());
                  ps.setString(2, txt_price.getText());
                  ps.setInt(3, Integer.parseInt(txt_id.getText()));
                  ps.executeUpdate();
                  Show_Product_In_JTable();
                  JOptionPane.showMessageDialog(null,"product updated");
                  
              } catch (SQLException ex) {
                  Logger.getLogger(frame2.class.getName()).log(Level.SEVERE, null, ex);
              }
            
        }
        //update with Image
        else{
          InputStream img =null;
            try{
             img = new FileInputStream(new File(ImgPath));
          
            UpdateQuery= "Update product set name = ?, price = ?, image = ? WHERE id = ? ";
                  ps = con.prepareStatement(UpdateQuery);
                  ps.setString(1,txt_name.getText());
                  ps.setString(2, txt_price.getText());
                  ps.setBlob(3,img);
                  ps.setInt(4, Integer.parseInt(txt_id.getText()));
                  
                  ps.executeUpdate();
                  Show_Product_In_JTable();
                  JOptionPane.showMessageDialog(null,"product updated");
          }
          catch(Exception e){
               JOptionPane.showMessageDialog(null ,"notupdate");
          }
      }
          
      }
      else{
              JOptionPane.showMessageDialog(null ,"one or more fields are empty or wrong");
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       JFileChooser file=new JFileChooser();
       file.setCurrentDirectory(new File(System.getProperty("user.home")));
       FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");
       file.addChoosableFileFilter(filter);
       int result=file.showSaveDialog(null);
       if(result==JFileChooser.APPROVE_OPTION){
           File selectedFile=file.getSelectedFile();
           String path=selectedFile.getAbsolutePath();
           lbl_image.setIcon(ResizeImage(path,null));
           ImgPath=path;
       }
       else{
           System.out.println("No file selected");
       }
           
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(!txt_id.getText().equals("")){
           PreparedStatement ps= null;
        Connection con =getConnection();
         try {
         
             ps = con.prepareStatement("DELETE FROM product where id = ?");
             int id = Integer.parseInt(txt_id.getText());
             ps.setInt(1, id);
             ps.executeUpdate();
             Show_Product_In_JTable();
             JOptionPane.showMessageDialog(null, "product deleted");
             } 
             catch (SQLException ex) {
             Logger.getLogger(frame2.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "product deleted");
             }
     }
     else{
         JOptionPane.showMessageDialog(null, "Product not deleted : no id to delete");
     }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InsertActionPerformed
      if(checkInputs() && ImgPath != null){
        try {
         Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/store","omer","omer");
         PreparedStatement ps=con.prepareStatement("insert into product(name,price,image) values(?,?,?)");
         ps.setString(1, txt_name.getText());
         ps.setString(2, txt_price.getText());
         InputStream img = new FileInputStream(new File(ImgPath));
         ps.setBlob(3, img );
         ps.executeUpdate();
         Show_Product_In_JTable();
           JOptionPane.showMessageDialog(null, "data insert"); 
        } 
        
        catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
             } 
        catch (FileNotFoundException ex) {
              Logger.getLogger(frame2.class.getName()).log(Level.SEVERE, null, ex);
          }
             
             
             
         }else{
             JOptionPane.showMessageDialog(null, "one or more field are empty"); 
             
         }      
        
    }//GEN-LAST:event_Btn_InsertActionPerformed

    private void JTable_ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_ProductsMouseClicked
       int index = JTable_Products.getSelectedRow();
       ShowItem(index);
    }//GEN-LAST:event_JTable_ProductsMouseClicked

    private void Btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FirstActionPerformed
         pos=0;
        ShowItem(pos);
    }//GEN-LAST:event_Btn_FirstActionPerformed

    private void Btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LastActionPerformed
       pos=getProductList().size()-1;
        ShowItem(pos);
       
        
    }//GEN-LAST:event_Btn_LastActionPerformed

    private void Btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NextActionPerformed
       pos++;
       if(pos>=getProductList().size()){
           pos=getProductList().size()-1;
           
       }
        ShowItem(pos);
        
    }//GEN-LAST:event_Btn_NextActionPerformed

    private void Btn_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PreviousActionPerformed
        pos--;
        if(pos<0){
            pos=0;
            
        }
        ShowItem(pos);
    }//GEN-LAST:event_Btn_PreviousActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      frame1 obj=new frame1();
      obj.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_First;
    private javax.swing.JButton Btn_Insert;
    private javax.swing.JButton Btn_Last;
    private javax.swing.JButton Btn_Next;
    private javax.swing.JButton Btn_Previous;
    private javax.swing.JTable JTable_Products;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables

    private void printf(String error) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
